name: Deploy

on:
  push:
    branches:
      - dev-publish

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm docs:build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: .vitepress/dist

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Clear main branch
        run: |
          git rm -r .

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto update portfolio"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: .vitepress/dist

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
